### ISSUE TITLE
Hope the sharing code of scripts/segm_utils.py

### ISSUE THREAD

**Issue by CHNxindong** [soon-yau/upgpt#27]
Hi, Soon Yau. I hope to fine tune the UPGPT with more data. I have encountered a problem:

I followed the steps in DATA_README.md, but I find that there is no scripts.segm_utils in command 'python scripts/segment.py':
![image](https://github.com/soon-yau/upgpt/assets/20262070/676d9c7f-e025-4bd0-873c-6152d4a1828c)

Can you kindly share the code of scripts/segm_utils.py. 

Thanks for your attention!

**Comment by soon-yau** [comment]
You don't need that file, it is an old file to extract fashion segmentation from MM dataset. In fact, I haven't included the pipeline to create the dataset which is quite involving.  I will only have time to do it in 1-2 weeks later.

**Comment by CHNxindong** [comment]
Thanks for your response! Looking forward to the dataset pipeline.
