### ISSUE TITLE
Hope the processed data for 512x384

### ISSUE THREAD

**Issue by CHNxindong** [soon-yau/upgpt#28]
Thanks for your great work. Can you kindly provide the processed data and checkpoint for 512x384?

**Comment by soon-yau** [comment]
You can download all the generated test images from [release](https://github.com/soon-yau/upgpt/releases/download/v1.0.0/results_v1.zip) which include the 512x256 (cropped) images. 

Unfortunately, I'm unable to find the 512x384 checkpoint used in the paper. As an alternative, you can perhaps use the 256+upscale in the streamlit app to create the higher resolution.

**Comment by CHNxindong** [comment]
I get it. Thanks for your kind reply!
